<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup Label="Globals">
		<SccProjectName>SAK</SccProjectName>
		<SccProvider>SAK</SccProvider>
		<SccAuxPath>SAK</SccAuxPath>
		<SccLocalPath>SAK</SccLocalPath>
	</PropertyGroup>

	<PropertyGroup>
		<Description>This Package Contain Useful Library And Extention Method For Easy Develop High Tech Asp.Net Application.

ForExample : Implementation Of HttpRequestTools, ClientInfo, ExtentionMethod, ...		</Description>
		<PackageTags>Asp Asp.NetCore ExtentionMethod HttpRequestTools ClientInfo</PackageTags>
		<PackageReleaseNotes>For Contact Us Please Send Mail Or Call To :

Tel : +989301919109
Mail : mehrannoruzi@gmail.com		</PackageReleaseNotes>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Http.Polly" />
		<PackageReference Include="Polly" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\Core\Bat.Core\Bat.Core.csproj" />
	</ItemGroup>

</Project>
