<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup Label="Globals">
		<SccProjectName>SAK</SccProjectName>
		<SccProvider>SAK</SccProvider>
		<SccAuxPath>SAK</SccAuxPath>
		<SccLocalPath>SAK</SccLocalPath>
	</PropertyGroup>

	<PropertyGroup>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<Description>This Package Contain Useful Library And Extension Method For Easy Develop High Tech .Net Application.

ForExample : Implementation Of StackExchange Library Of Redis, ...
		</Description>
		<PackageTags>Cache Redis StackExchange ExtensionMethods RedisConfiguration</PackageTags>
		<PackageReleaseNotes>For Contact Us Please Send Mail Or Call To :

Tel : 09301919109
Mail : mehrannoruzi@gmail.com</PackageReleaseNotes>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="appsettings.json" />
	</ItemGroup>

	<ItemGroup>
	  <Content Include="appsettings.json">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	    <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
	    <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
	  </Content>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Caching.Hybrid" />
		<PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" />
		<PackageReference Include="Microsoft.Extensions.Configuration" />
		<PackageReference Include="StackExchange.Redis" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\Core\Bat.Core\Bat.Core.csproj" />
	</ItemGroup>

</Project>
