<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup Label="Globals">
		<SccProjectName>SAK</SccProjectName>
		<SccProvider>SAK</SccProvider>
		<SccAuxPath>SAK</SccAuxPath>
		<SccLocalPath>SAK</SccLocalPath>
	</PropertyGroup>

	<PropertyGroup>
		<Product>Bat.Di</Product>
		<Description>This Package Contain Useful Library And Extention Method For Dependency Injection in High Tech .Net Application.

ForExample : ExtensionMethods For Dynamically Register Service And Componnent Base On Inherit From ITransientInjection, IScopedInjection Or ISingletonInjection</Description>
		<PackageTags>Ioc Di Dependency DependencyInjection AutofacExtension ExtentionMethod Autofac DryIoc</PackageTags>
		<PackageReleaseNotes>For Contact Us Please Send Mail Or Call To :

Tel : +989301919109
Mail : mehrannoruzi@gmail.com		</PackageReleaseNotes>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Autofac.Extensions.DependencyInjection" />
		<PackageReference Include="DryIoc.Microsoft.DependencyInjection" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\Core\Bat.Core\Bat.Core.csproj" />
	</ItemGroup>

</Project>
