<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Nullable>disable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Moq" />
		<PackageReference Include="AutoBogus" />
		<PackageReference Include="NSubstitute" />
		<PackageReference Include="MockQueryable.Moq" />
		<PackageReference Include="AutoFixture.AutoMoq" />
		<PackageReference Include="MockQueryable.EntityFrameworkCore" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\DataAccess\Bat.EntityFrameworkCore.Tools\Bat.EntityFrameworkCore.Tools.csproj" />
	</ItemGroup>

</Project>
