<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup Label="Globals">
		<SccProjectName>SAK</SccProjectName>
		<SccProvider>SAK</SccProvider>
		<SccAuxPath>SAK</SccAuxPath>
		<SccLocalPath>SAK</SccLocalPath>
	</PropertyGroup>

	<PropertyGroup>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<Description>This Package Contain Useful Library And Extension Method For Easy Develop High Tech .Net Application With EntityFrameworkCore.

ForExample : Implementation Of Custom Entity Validation, Extension Method, Bulk Operation, Annotation, StoredProcedure ...</Description>
		<PackageTags>EntityValidation ExtensionMethod Annotation StoredProcedure ModelBuilder</PackageTags>
		<PackageReleaseNotes>For Contact Us Please Send Mail Or Call To :

Tel : +989301919109
Mail : mehrannoruzi@gmail.com
		</PackageReleaseNotes>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="EFCore.BulkExtensions.SqlServer" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\Core\Bat.Core\Bat.Core.csproj" />
	  <ProjectReference Include="..\Bat.EntityFrameworkCore\Bat.EntityFrameworkCore.csproj" />
	</ItemGroup>

</Project>
